version: '3'

services:
  database:
    image: 'postgres:13'
    restart: 'always'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'root'
      POSTGRES_DB: 'main-db'
    volumes:
      - './data/postgres:/var/lib/postgresql/data/'
    networks:
      - coderscamp-net

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - '${PGADMIN_PORT:-5050}:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: 'root@coderscamp.com'
      PGADMIN_DEFAULT_PASSWORD: 'root'
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin/storage/
    networks:
      - coderscamp-net

networks:
  coderscamp-net:
    driver: bridge
