import {
  BabelIcon,
  BootstrapIcon,
  Css3Icon,
  EslintIcon,
  ExpressIcon,
  GithubIcon,
  GitIcon,
  HerokuIcon,
  Html5Icon,
  JavascriptIcon,
  JestIcon,
  MongodbIcon,
  NestjsIcon,
  NetlifyIcon,
  NodejsIcon,
  NpmIcon,
  PostgresqlIcon,
  PrettierIcon,
  ReactOriginalIcon,
  ReactRouterIcon,
  ReduxOriginalIcon,
  TypescriptPlainIcon,
  VscodePlainIcon,
  WebpackPlainIcon,
  YarnOriginalIcon,
} from '@coderscamp/ui/icons';

export const techNames = [
  { name: 'BabelIcon', value: <BabelIcon /> },
  { name: 'BootstrapIcon', value: <BootstrapIcon /> },
  { name: 'Css3Icon', value: <Css3Icon /> },
  { name: 'EslintIcon', value: <EslintIcon /> },
  { name: 'ExpressIcon', value: <ExpressIcon /> },
  { name: 'GithubIcon', value: <GithubIcon /> },
  { name: 'GitIcon', value: <GitIcon /> },
  { name: 'HerokuIcon', value: <HerokuIcon /> },
  { name: 'Html5Icon', value: <Html5Icon /> },
  { name: 'JavascriptIcon', value: <JavascriptIcon /> },
  { name: 'JestIcon', value: <JestIcon /> },
  { name: 'MongodbIcon', value: <MongodbIcon /> },
  { name: 'NestjsIcon', value: <NestjsIcon /> },
  { name: 'NetlifyIcon', value: <NetlifyIcon /> },
  { name: 'NodejsIcon', value: <NodejsIcon /> },
  { name: 'NpmIcon', value: <NpmIcon /> },
  { name: 'PostgresqlIcon', value: <PostgresqlIcon /> },
  { name: 'PrettierIcon', value: <PrettierIcon /> },
  { name: 'ReactOriginalIcon', value: <ReactOriginalIcon /> },
  { name: 'ReactRouterIcon', value: <ReactRouterIcon /> },
  { name: 'ReduxOriginalIcon', value: <ReduxOriginalIcon /> },
  { name: 'TypescriptPlainIcon', value: <TypescriptPlainIcon /> },
  { name: 'VscodePlainIcon', value: <VscodePlainIcon /> },
  { name: 'WebpackPlainIcon', value: <WebpackPlainIcon /> },
  { name: 'YarnOriginalIcon', value: <YarnOriginalIcon /> },
];
