openapi: 3.0.0
info:
  title: CodersCamp REST API
  description: Internal REST API for CodersCamp
  version: '1.0'
  contact: {}
tags:
  - name: Authentication
    description: Internal jwt token based authentication server.
  - name: User Profile
    description: Personal data about users.
  - name: User Account
    description: Operations related to lifecycle of user account.
  - name: Courses
    description: CRUD for platform courses.
  - name: Learning Materials
    description: Generating and retrieving checklist URL.
  - name: Process.st
    description: WebHooks endpoints. Integration with checklist platform.
    externalDocs:
      description: Find out more
      url: https://www.process.st/webhooks/
servers:
  - url: /api
    description: REST API v1
paths:
  /users:
    get:
      operationId: UserProfile_getAll
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - User Profile
        - User Account
  /users/me:
    get:
      operationId: UserProfile_getMe
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - User Profile
        - User Account
  /courses:
    get:
      operationId: Courses_getAll
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - Courses
    post:
      operationId: Courses_createCourse
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CourseBody'
      responses:
        '201':
          description: ''
      tags:
        - Courses
  /auth/login:
    post:
      operationId: Auth_login
      summary: ''
      requestBody:
        description: api credentials
        content: {}
      parameters: []
      responses:
        '204':
          description: Authorization token successfully received as cookie
      tags:
        - Authentication
        - User Account
  /auth/logout:
    post:
      operationId: Auth_logout
      parameters: []
      responses:
        '201':
          description: ''
      tags:
        - Authentication
        - User Account
  /learning-materials:
    post:
      operationId: LearningMaterialsUrl_generateUserLearningResourcesUrl
      parameters: []
      responses:
        '204':
          description: ''
      tags:
        - Learning Materials
    get:
      operationId: LearningMaterials_getLearningMaterial
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - Learning Materials
  /user-registration:
    post:
      operationId: UserRegistration_register
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterBody'
      responses:
        '204':
          description: ''
      tags:
        - User Registration
        - User Account
  /process-st/events/task-checked-unchecked:
    post:
      operationId: LearningMaterialsTask_taskCheckedUnchecked
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - Process.st
  /email-confirmation:
    post:
      operationId: EmailConfirmation_emailConfirmation
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmailConfirmationBody'
      responses:
        '204':
          description: ''
      tags:
        - Email Confirmation
        - User Registration
        - User Account
  /course-progress:
    get:
      operationId: CourseProgress_getCourseProgress
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - Course Progress
components:
  schemas:
    CourseBody:
      type: object
      properties: {}
    RegisterBody:
      type: object
      properties: {}
    EmailConfirmationBody:
      type: object
      properties: {}
