import { useState } from 'react';
import Head from 'next/head';

import { Button } from '@coderscamp/ui/components/Button';

const Home = () => {
  const [count, setCount] = useState(0);

  const handleClick = () => setCount((prev) => prev + 1);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Button onClick={handleClick}>count is: {count}</Button>
    </>
  );
};

export default Home;
