name: Pull Request

on:
  pull_request:
    branches: [main]

jobs:
  pr-name:
    name: Check PR name
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amannn/action-semantic-pull-request@v3.4.0
        with:
          scopes: |
            api
            panel
            website
            ui
            core
            deps
          requireScope: false
          validateSingleCommit: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  branch-name:
    name: Check branch name
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-branch-name@master
        with:
          regex: "^(issue-[0-9]+|chore)-.+$"
          ignore: main
