name: Semantic Pull Request

on:
  pull_request:
    branches: [main]

jobs:
  check:
    name: "Check PR name"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amannn/action-semantic-pull-request@v3.4.0
        with:
          types: |
            build
            chore
            ci
            docs
            feat
            fix
            perf
            refactor
            revert
            style
            test
          scopes: |
            api
            panel
            website
            ui
            core
            deps
          requireScope: false
          validateSingleCommit: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
