name: "Semantic Pull Request"

on:
  pull_request:
    branches:
      - main
    types: [assigned, opened, synchronize, reopened, edited]

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: amannn/action-semantic-pull-request@v3.4.0
        with:
          types: |
            build
            ci
            docs
            feat
            fix
            perf
            refactor
            style
            test
          scopes: |
            api
            panel
            website
            ui
            core
          requireScope: false
          validateSingleCommit: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

