name: CodersCamp Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies 
        run: yarn install --immutable
      - name: run affected tests 
        run: yarn test --onlyChanged
      
  es-Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies 
        run: yarn install --immutable
      - name: Run ESLint
        run: yarn eslint --cache
  typescript-compiler:
    name: typecheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install node v14
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: install dependencies
      run: yarn install --immutable
    - name: tsc compile webside
      run: yarn typecheck
